config/routes.rb
Rails.application.routes.draw do
  resources :patients
  root :to => 'patients#index'

end

app/models/patient.rb
class Patient < ActiveRecord::Base

def self.search(search)
    if search
      self.where("name like ?", "%#{search}%")
      #self.where(:identification => "%#{search}%".to_i)
      
    else
      self.all
    end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.search(params[:search])
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:name, :identification, :chief_response, :age, :walking, :mental_state, :hospital_taken_to, :allergies, :any_other_details,:color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Triage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/patients/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@patient) do |f| %>
    <% if @patient.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>
  
        <ul>
        <% @patient.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :color %><br>
      <%= select(:patient, :color, ['Red','Green','Yellow','Black']) %>
    </div>
    <div class="field">
      <%= f.label :identification %><br>
      <%= f.number_field :identification %>
    </div>
    <div class="field">
      <%= f.label :chief_response %><br>
      <%= f.text_field :chief_response %>
    </div>
    <div class="field">
      <%= f.label :age %><br>
      <%= f.number_field :age %>
    </div>
    <div class="field">
      <%= f.label :walking %><br>
      <%= select(:patient, :walking, ['yes','no']) %>
    </div>
    <div class="field">
      <%= f.label :mental_state %><br>
      <%= select(:patient, :mental_state, ['stable','unstable']) %>
    </div>
    <div class="field">
      <%= f.label :hospital_taken_to %><br>
      <%= f.text_field :hospital_taken_to %>
    </div>
    <div class="field">
      <%= f.label :allergies %><br>
      <%= f.text_field :allergies %>
    </div>
    <div class="field">
      <%= f.label :any_other_details %><br>
      <%= f.text_field :any_other_details %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

  </div>
</div>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
  <p id="notice"><%= notice %></p>
  <h1 class="page-header">Listing Patients</h1>
   <h1 class= "page-header"><span class='special-color-black'> Black <%= Patient.where(:color=>'Black').count  %></span> ,<span class='special-color-red'> Red <%= Patient.where(:color=>'Red').count %></span> ,<span class='special-color-green'> Green <%= Patient.where(:color=>'Green').count %></span>,<span class='special-color-yellow'> Yellow <%= Patient.where(:color=>'Yellow').count %></span></h1>  
  <div class='page-header'>
    <%=form_tag patients_path, :method => 'get' do %>
    <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
    </p>
  <%end %>
  </div>
  
  <table class="class=span9 center-table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Identification</th>
        <th>Chief response</th>
        <th>Age</th>
        <th>Walking</th>
        <th>Mental state</th>
        <th>Hospital taken to</th>
        <th>Allergies</th>
        <th>Any other details</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @patients.each do |patient| %>
        <tr>
          <% if patient.color == 'Red' %>
          <td class = 'special-color-red'> <%= patient.name %> </td>
          <%elsif patient.color =='Yellow'%>
          <td class = 'special-color-yellow'> <%= patient.name %> </td>
          <%elsif patient.color =='Green'%>
          <td class = 'special-color-green'> <%= patient.name %> </td>
          <%elsif patient.color =='Black'%>
          <td class = 'special-color-black'> <%= patient.name %> </td>
          <%end%>
          <td><%= patient.identification %></td>
          <td><%= patient.chief_response %></td>
          <td><%= patient.age %></td>
          <td><%= patient.walking %></td>
          <td><%= patient.mental_state %></td>
          <td><%= patient.hospital_taken_to %></td>
          <td><%= patient.allergies %></td>
          <td><%= patient.any_other_details %></td>
          <td><%= link_to 'Show', patient %></td>
          <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
          <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>

<p>
  <strong>Identification:</strong>
  <%= @patient.identification %>
</p>

<p>
  <strong>Chief response:</strong>
  <%= @patient.chief_response %>
</p>

<p>
  <strong>Age:</strong>
  <%= @patient.age %>
</p>

<p>
  <strong>Walking:</strong>
  <%= @patient.walking %>
</p>

<p>
  <strong>Mental state:</strong>
  <%= @patient.mental_state %>
</p>

<p>
  <strong>Hospital taken to:</strong>
  <%= @patient.hospital_taken_to %>
</p>

<p>
  <strong>Allergies:</strong>
  <%= @patient.allergies %>
</p>

<p>
  <strong>Any other details:</strong>
  <%= @patient.any_other_details %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>